# 服务端口
server:
  port: 8002

# 服务名
spring:
  application:
    name: guli-vod
  # 环境设置 dev、test、prod
  profiles:
    active: dev
  # 设置文件上传大小
  servlet:
    multipart:
      # 最大上传单个文件大小：默认1M
      max-file-size: 1024MB
      # 最大置总上传的数据大小 ：默认10M
      max-request-size: 1024MB


# 阿里云oss相关参数  不同的服务器，地址不同
aliyun:
  vod:
    file:
      accessKeyId: xxxxxxxx
      accessKeySecret: xxxxxxxxxxxx


# 服务注册
# 指定注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka/
  # eureka服务器上获取的是服务器的ip地址，否则是主机名
  instance:
    prefer-ip-address: true