server:
  port: 7002

# 配置相关服务注册内容
eureka:
  client:
    # 是否将自己注册到 Eureka 服务器中，本身就是服务器，不需要注册
    allow-redirects: false
    # 是否从 Eureka 中获取注册信息
    fetch-registry: false
    # Eureka客户端与Eureka服务端进行通信的地址
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/

