# 服务端口
server:
  port: 8001

# 服务名
spring:
  application:
    name: guli-edu
  # 环境设置 dev、test、prod
  profiles:
    active: dev
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_edu?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis 日志（打印sql）
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #配置mapper xml文件的路径
  mapper-locations: classpath:com/guli/edu/mapper/xml/*.xml

# 服务注册
# 指定注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka/
  # eureka服务器上获取的是服务器的ip地址，否则是主机名
  instance:
    prefer-ip-address: true

# 阿里云oss相关参数  不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: xxxx.xxxx.com
      accessKeyId: xxxxxxxxxxxxxxxxxxx
      accessKeySecret: xxxxxxxxxxxxxxxxxxx
      #阿里云oss bucket名，即存储的文件名
      bucketName: edu-teacher0114


